---
title: "SFBay Rocky Shore Survey analyses"
author: "Karina J. Nielsen"
date: "Last compiled on `r format(Sys.time(), '%d %B %Y')`"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "left",
  fig.width = 6,
  fig.height = 4,
  dev = "png",
  cache = TRUE
)


# echo = FALSE means code will not print, by default
#cache = TRUE saves output results of all chunks so that they do not ned to be rerun

```


```{r library, include=FALSE}
library("easypackages")
my_packages <- c("renv", "easypackages",  "here", "ggthemes", "gridExtra", "tidyverse", "lubridate", "patchwork", "tinytex", "bookdown", "ggpubr", "wesanderson", "pals", "ggridges") 
libraries(my_packages)

# Install packages if needed
# install.packages("easypackages")
# packages(my_packages) 

# checks to make sure the packages needed are loaded and asks before installing to confirm install in the console window
```

```{r renv, include=FALSE}
#Track/maintain package versions in workflow

#renv::init # to initialize a new project-local environment with a private R library
#run as needed later in the project to capture required package versions

renv::snapshot() 

#NB must respond and affirm actions in console or you will see the spinning wheel....
#reference for renv workflow: https://rstudio.github.io/renv/articles/renv.html

```

```{r functions}

#As needed...

```


```{r here, include=FALSE}

## Confirm working directory for project
here::here() # use this to work with sub-directories less awkwardly and share projects across users/machines more easily.
```



```{r read, message=FALSE}
##Reads in *.csv data files to tibbles and keeps first row as column names

rqs <- read_csv(here::here ("data","sfbay_rockweed_quadrat_surveys.csv"), col_names = TRUE) 

rqs.loc <- read_csv(here::here ("data","sfbay_rockweed_site_names_locations.csv"), col_names = TRUE) 

sizes <- read_csv(here::here ("data","sfbay_rockweed_quadrat_invert_sizes.csv"), col_names = TRUE)


```

```{r wrangle, include=FALSE}

# Updates rqs$date formatting from chr to POSIXct
rqs <- mutate(rqs, date = as.POSIXct(rqs$date, tz = "America/Los_Angeles", format = "%m/%d/%Y")) 

# Convert zone character variable to factor variable with ordered levels
rqs <- mutate(rqs, zone = as.factor(rqs$zone))
ordered(rqs$zone, levels = c("Low", "Mid", "High"))

#convert site names to ordered factor - ordered around bay perimeter from SF Marina to Miller Knox
rqs <- rename(rqs, site_name = site)
rqs <- mutate(rqs, site_name = as.factor(rqs$site_name))
ordered(
  rqs$site_name,
  levels = c(
    "SF Marina",
    "Horseshoe Bay",
    "Dunphy Park",
    "Brickyard Park",
    "RTC Beach",
    "RTC Theater",
    "RTC North Dock",
    "Pt. Chauncey",
    "Pt. Chauncey Beach S",
    "Pt. Chauncey Beach N",
    "Paradise Beach Park",
    "Paradise Cay",
    "San Quentin Beach",
    "Starkweather Park",
    "Pt. San Pablo",
    "Pt. Orient N",
    "Pt. Orient S",
    "Pt. Molate",
    "Keller Beach",
    "Miller Knox"
  )
)


# merges rqs and rqs.loc by site codes

rqs2 <- dplyr::full_join(rqs, rqs.loc, by = "site_code")
rqs2

# creates column with RTC vs. all other sites for 'spotlighting" in graphs, reorders some columns

rqs3 <- rqs2 %>% 
  mutate(RTC_sites = case_when(
        site_code %in% c("PBS", "PCR", "PCW", "PCB", "PCC", "RTCR", "RTCC", "RTCS", "SQB")  ~ "RTC",
        site_code %in% c("SWR", "SFMS", "RRR", "POC", "POB", "PMB", "MKR", "KBB", "HBR", "DPR", "BPB")  ~ "other"),
        .after = site_name.x
  )%>%
  relocate(lat, .after = site_code)%>%
  relocate(long, .after = lat)%>%
  relocate(bay_perim_order, .after = site_code) %>% 
  mutate(bay_perim_order = as.factor(rqs3$bay_perim_order))


rqs3$RTC_sites <- ordered(rqs3$RTC_sites, levels = c("RTC", "other")) 
rqs3 <- rename(rqs3, site_name = site_name.x)
rqs3 <- select(rqs3, -site_name.y)


rqs3 

# Creates site x zone summary data sets and merges with site type 

## Mid zone

rqs4 <- rqs3 %>%
  filter(zone == "Mid") %>%
  drop_na(fucus_pc, oyster_n) %>%
  group_by(site_code) %>%                                                          # Specify group indicator
  summarise(
    fucus_pc_avg = mean(fucus_pc),
    oyster_n_avg = mean(oyster_n),
    .groups = "keep"
  )                                                                                # Specify column, function, and new name
rqs4

rqs5 <- full_join(rqs4, rqs.loc, by = "site_code")
rqs5 <- rqs5 %>%
  select(site_code, fucus_pc_avg, oyster_n_avg, site_type, site_type2)
rqs5

##Low zone

rqs6 <- rqs3 %>%
  filter(zone == "Low") %>%
  drop_na(fucus_pc, oyster_n) %>%
  group_by(site_code) %>%                                                         # Specify group indicator
  summarise(
    fucus_pc_avg = mean(fucus_pc),
    oyster_n_avg = mean(oyster_n),
    .groups = "keep"
  )                                                                              # Specify column, function, and new name
rqs6

rqs7 <- full_join(rqs6, rqs.loc, by = "site_code")
rqs7 <- rqs7 %>%
  select(site_code, fucus_pc_avg, oyster_n_avg, site_type, site_type2)
rqs7

#sizes

# Convert zone character variable to factor variable with ordered levels
sizes1 <- sizes
mutate(sizes1, site_name = as.factor(sizes1$site_name))
ordered(
  sizes1$site_name,
  levels = c(
    "SF Marina",
    "Horseshoe Bay",
    "Dunphy Park",
    "Brickyard Park",
    "RTC Beach",
    "RTC Theater",
    "RTC North Dock",
    "Pt. Chauncey",
    "Pt. Chauncey Beach S",
    "Pt. Chauncey Beach N",
    "Paradise Beach Park",
    "Paradise Cay",
    "San Quentin Beach",
    "Starkweather Park",
    "Pt. San Pablo",
    "Pt. Orient N",
    "Pt. Orient S",
    "Pt. Molate",
    "Keller Beach",
    "Miller Knox"
  )
)

```

# Plots of quadrat data from each transect {#anchor}


```{r fucus x zone, include=TRUE, fig.width = 6, fig.height = 5}

# Mid + low zone Fucus cover x site, ordered around SFBay perimeter

fucus_p1 <- rqs3 %>%
  drop_na(fucus_pc) %>%
  filter(zone != "High") %>%
  ggplot (aes(x = bay_perim_order, y = fucus_pc, fill = zone)) +
  geom_boxplot(outlier.size = 0, position = position_dodge2(preserve = "single")) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  theme_few() +
  scale_fill_few(palette = "Light") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
  breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
  labels = c(
    "SF Marina",
    "Horseshoe Bay",
    "Dunphy Park",
    "Brickyard Park",
    "RTC Beach",
    "RTC Theater",
    "RTC North Dock",
    "Pt. Chauncey",
    "Pt. Chauncey Beach S",
    "Pt. Chauncey Beach N",
    "Paradise Beach Park",
    "Paradise Cay",
    "San Quentin Beach",
    "Starkweather Park",
    "Pt. San Pablo",
    "Pt. Orient N",
    "Pt. Orient S",
    "Pt. Molate",
    "Keller Beach",
    "Miller Knox"
  )
  ) +
  
  labs(x = NULL,  y = expression(paste(italic(" Fucus distichus"), " cover (%)"))) 


fucus_p1

```




```{r fucus mid, include=TRUE}

#Mid zone Fucus cover x site, ordered around SFBay perimeter, highlighting RTC sites

fucus_p2 <- rqs3 %>%
  drop_na(fucus_pc) %>%
  filter(zone == "Mid") %>%
  ggplot (aes(x = bay_perim_order, y = fucus_pc, fill = RTC_sites)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 2,
               jitter.width = 1,
               seed = 7
             )) +
  scale_fill_manual(values = c("darkolivegreen4", "light grey"), drop=FALSE) +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
    labels = c(
      "SF Marina",
      "Horseshoe Bay",
      "Dunphy Park",
      "Brickyard Park",
      "RTC Beach",
      "RTC Theater",
      "RTC North Dock",
      "Pt. Chauncey",
      "Pt. Chauncey Beach S",
      "Pt. Chauncey Beach N",
      "Paradise Beach Park",
      "Paradise Cay",
      "San Quentin Beach",
      "Starkweather Park",
      "Pt. San Pablo",
      "Pt. Orient N",
      "Pt. Orient S",
      "Pt. Molate",
      "Keller Beach",
      "Miller Knox"
    ),
    drop=FALSE
  ) +
  labs(x = NULL,  y = expression(paste(italic(" Fucus distichus"), " cover (%)"))) +
  ggtitle("Mid Zone")

fucus_p2

```

```{r fucus low, include=TRUE}

#Low zone Fucus cover x site, ordered around SFBay perimeter, highlighting RTC sites

fucus_p3 <- rqs3 %>%
  drop_na(fucus_pc) %>%
  filter(zone == "Low") %>%
  ggplot (aes(x = bay_perim_order, y = fucus_pc, fill = RTC_sites)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 2,
               jitter.width = 1,
               seed = 7
             )) +
  scale_fill_manual(values = c("darkolivegreen4", "light grey"), drop=FALSE) +   
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
    labels = c(
      "SF Marina",
      "Horseshoe Bay",
      "Dunphy Park",
      "Brickyard Park",
      "RTC Beach",
      "RTC Theater",
      "RTC North Dock",
      "Pt. Chauncey",
      "Pt. Chauncey Beach S",
      "Pt. Chauncey Beach N",
      "Paradise Beach Park",
      "Paradise Cay",
      "San Quentin Beach",
      "Starkweather Park",
      "Pt. San Pablo",
      "Pt. Orient N",
      "Pt. Orient S",
      "Pt. Molate",
      "Keller Beach",
      "Miller Knox"
    ),
    drop=FALSE
  ) +
  labs(x = NULL,  y = expression(paste(italic(" Fucus distichus"), " cover (%)"))) +
  ggtitle("Low Zone")

fucus_p3 
```

```{r fucus mid sitetype, include=TRUE}

#Mid zone Fucus cover x sitetype

fucus_p4 <- rqs5 %>%
  filter(site_type2 != "blocks") %>%
  filter(site_type2 != "seawall" ) %>%
  ggplot (aes(x = site_type2, y = fucus_pc_avg, fill=site_type2)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 0.1,
               jitter.width = 0.1,
               seed = 7
             )) +
  scale_fill_brewer(palette = "Dark2") +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  labs(x = NULL,  y = expression(paste(italic(" Fucus distichus"), " cover (%)"))) +
  ggtitle("Mid Zone")

fucus_p4 
```

```{r fucus low sitetype, include=true}

#Low zone Fucus cover x sitetype

fucus_p5 <- rqs7 %>%
  filter(site_type2 != "blocks") %>%
  filter(site_type2 != "seawall") %>%
  drop_na(fucus_pc_avg) %>%
  ggplot (aes(x = site_type2, y = fucus_pc_avg, fill = site_type2)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 0.1,
               jitter.width = 0.5,
               seed = 7
             )) +
  scale_fill_brewer(palette = "Dark2") +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 0,
    vjust = 0.5,
    hjust = 0.5,
    size = rel(1.2)
  )) +
  labs(x = NULL,  y = expression(paste(italic(" Fucus distichus"), " cover (%)"))) +
  ggtitle("Low Zone")

fucus_p5 
```


```{r ostrea x zone, include=TRUE, fig.width = 9, fig.height = 6}

#Mid + Low zone native oyster density (no. per m2) x site, ordered around SFBay perimeter

oysters_p1 <- rqs3 %>%
  drop_na(oyster_n) %>%
  filter(zone != "High") %>%
  ggplot (aes(
    x = bay_perim_order,
    y = (oyster_n * 4),
    fill = zone
  )) + # density per Q * 4 = no/m2
  geom_boxplot(outlier.size = 0, position = position_dodge2(preserve = "single")) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  theme_few() +
  scale_fill_few(palette = "Light") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
    labels = c(
      "SF Marina",
      "Horseshoe Bay",
      "Dunphy Park",
      "Brickyard Park",
      "RTC Beach",
      "RTC Theater",
      "RTC North Dock",
      "Pt. Chauncey",
      "Pt. Chauncey Beach S",
      "Pt. Chauncey Beach N",
      "Paradise Beach Park",
      "Paradise Cay",
      "San Quentin Beach",
      "Starkweather Park",
      "Pt. San Pablo",
      "Pt. Orient N",
      "Pt. Orient S",
      "Pt. Molate",
      "Keller Beach",
      "Miller Knox"
    )
  )
  
  
  oysters_p1
```

```{r ostrea mid, include=TRUE}

#Mid zone native oyster density (no. per m2) x site, ordered around SFBay perimeter, highlighting RTC sites

oysters_p2 <- rqs3 %>%
  drop_na(oyster_n) %>%
  filter(zone == "Mid") %>%
  ggplot (aes(
    x = bay_perim_order,
    y = (oyster_n * 4),
    fill = RTC_sites
  )) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 2,
               jitter.width = 1,
               seed = 7
             )) +
  scale_fill_manual(values = c("coral", "light grey"), drop=FALSE) +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
    labels = c(
      "SF Marina",
      "Horseshoe Bay",
      "Dunphy Park",
      "Brickyard Park",
      "RTC Beach",
      "RTC Theater",
      "RTC North Dock",
      "Pt. Chauncey",
      "Pt. Chauncey Beach S",
      "Pt. Chauncey Beach N",
      "Paradise Beach Park",
      "Paradise Cay",
      "San Quentin Beach",
      "Starkweather Park",
      "Pt. San Pablo",
      "Pt. Orient N",
      "Pt. Orient S",
      "Pt. Molate",
      "Keller Beach",
      "Miller Knox"
    ),
    drop=FALSE
  ) +
  labs(x = NULL,  y = expression(paste(
    italic("Ostrea lurida "), "abundance ", " (no. ",  m ^ -2, ")"
  ))) +
  ggtitle("Mid Zone")

oysters_p2 

```

```{r ostrea low, include=TRUE}

#Low zone native oyster density (no. per m2) x site, ordered around SFBay perimeter, highlighting RTC sites

oysters_p3 <- rqs3 %>%
  drop_na(oyster_n) %>%
  filter(zone == "Low") %>%
  ggplot (aes(
    x = bay_perim_order,
    y = (oyster_n * 4),
    fill = RTC_sites
  )) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 2,
               jitter.width = 1,
               seed = 7
             )) +
  scale_fill_manual(values = c("coral", "light grey"), drop=FALSE) +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) +
  scale_x_discrete(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20),
    labels = c(
      "SF Marina",
      "Horseshoe Bay",
      "Dunphy Park",
      "Brickyard Park",
      "RTC Beach",
      "RTC Theater",
      "RTC North Dock",
      "Pt. Chauncey",
      "Pt. Chauncey Beach S",
      "Pt. Chauncey Beach N",
      "Paradise Beach Park",
      "Paradise Cay",
      "San Quentin Beach",
      "Starkweather Park",
      "Pt. San Pablo",
      "Pt. Orient N",
      "Pt. Orient S",
      "Pt. Molate",
      "Keller Beach",
      "Miller Knox"
    ),
    drop=FALSE
  ) +
  labs(x = NULL,  y = expression(paste(
    italic("Ostrea lurida "), "abundance ", " (no. ",  m ^ -2, ")"
  ))) +
  ggtitle("Low Zone")

oysters_p3
```

```{r ostrea mid sitetype, include=TRUE}

#Mid zone native oyster density (no. per m2) x sitetype

oyster_p4 <- rqs5 %>%
  filter(site_type2 != "blocks") %>%
  filter(site_type2 != "seawall") %>%
  drop_na(oyster_n_avg) %>%
  ggplot (aes(x = site_type2, y = oyster_n_avg * 4, fill = site_type2)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 0.5,
               jitter.width = 0.5,
               seed = 7
             )) +
  scale_fill_brewer(palette = "Set3") +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 0,
    vjust = 0.5,
    hjust = 0.5
  )) +
  labs(x = NULL,  y = expression(paste(
    italic("Ostrea lurida "), "abundance ", " (no. ",  m ^ -2, ")"
  ))) +
  ggtitle("Mid Zone")

oyster_p4 
```


```{r ostrea low sitetype, include=TRUE}

#Low zone oyster density (no. per m2) x sitetype

oyster_p5 <- rqs7 %>%
  filter(site_type2 != "blocks") %>%
  filter(site_type2 != "seawall") %>%
  drop_na(oyster_n_avg) %>%
  ggplot (aes(x = site_type2, y = oyster_n_avg * 4, fill = site_type2)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(pch = 21,
             position = position_jitterdodge(
               jitter.height = 0.5,
               jitter.width = 0.5,
               seed = 7
             )) +
  scale_fill_brewer(palette = "Set3") +
  theme_few() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(
    angle = 0,
    vjust = 0.5,
    hjust = 0.5,
    size = rel(1.2)
  )) +
  labs(x = NULL,  y = expression(paste(
    italic("Ostrea lurida "), "abundance ", " (no. ",  m ^ -2, ")"
  ))) +
  ggtitle("Low Zone")

oyster_p5 
```
## Rockweed, *Fucus distichus*

```{r Fig.1, fig.width = 6, fig.height = 8, fig.cap = " Rockweed (Fucus distichus) cover in the mid and low intertidal at survey sites. Colored fill indicates reference sites used for nature-based restoration and climate adaptation planning at the SF State Romberg Tiburon Campus."}

ggarrange(fucus_p2, fucus_p3, ncol=1, nrow=2,heights= c(1, 1), align = "v")

```
## Native oyster, *Ostrea lurida*

```{r Fig.2, fig.width = 6, fig.height = 8, fig.cap = " Native oyster (Ostrea lurida) abundance in the mid and low intertidal at survey sites. Colored fill indicates reference sites used for nature-based restoration and climate adaptation planning at the SF State Romberg Tiburon Campus."}

ggarrange(oysters_p2 + rremove("x.text"), oysters_p3, ncol=1, nrow=2,heights= c(0.75, 1), align = "v")

```
## Rockweed + native oysters by site type and zone
```{r Fig.3, fig.width = 4, fig.height = 6, fig.cap = " Cover of rockweed (Fucus distichus) in the mid and low intertidal by site type."}

ggarrange(fucus_p4 + rremove("x.text"), fucus_p5, ncol=1, nrow=2,heights= c(0.5, 0.55), align = "v")

```

```{r Fig.4, fig.width = 4, fig.height = 6, fig.cap = " Abundance of native oysters (Ostrea lurida) in the mid and low intertidal by site type."}

ggarrange(oyster_p4 + rremove("x.text"), oyster_p5, ncol=1, nrow=2,heights= c(0.5, 0.55), align = "v")

```

```{r, include=TRUE}
```


```{r, include=TRUE}
scat1 <- rqs3 %>%
  drop_na(fucus_pc, oyster_n) %>%
  filter(zone != "High") %>% 
  ggplot (aes(x = fucus_pc, y = oyster_n, color = zone)) +
  geom_point(size = 4, alpha=0.5) +
  theme_few()

scat1

```

```{r Fig.5, fig.width = 10, fig.height = 4, fig.cap = " Abundance of native oysters (Ostrea lurida) in the mid and low intertidal by site type."}
scat2 <- rqs3 %>%
  drop_na(oyster_n, oyster_scar_n) %>%
  filter(zone != "High") %>% 
  ggplot (aes(x = oyster_n, y = oyster_scar_n, color = site_name)) +
  geom_point(size = 3, alpha=0.6, position = position_jitterdodge()) +
  facet_wrap (~ zone)+
  theme_few()+
  guides(col = guide_legend(ncol = 2)) +
  scale_color_manual(values=as.vector(kelly(20)))  #pals color palettes issue: in ggplot2 the color vector CANNOT have names, as.vector() strips off the names from the polychrome colors

scat2
```


```{r}
sizes2 <- sizes1 %>%
  filter(taxon == "Oyster") %>% 
  select(site_name, size_mm)
sizes3 <-sizes2 %>%
  mutate(site_name = fct_reorder(site_name, size_mm))

sizes3 <-sizes2 %>%
  mutate(sizes2, site_name = as.factor(sizes2$site_name))
ordered(
  sizes2$site_name,
  levels = c(
    "Dunphy Park",
    "Brickyard Park",
    "RTC Beach",
    "RTC Theater",
    "RTC North Dock",
    "Pt. Chauncey",
    "Pt. Chauncey Beach S",
    "Pt. Chauncey Beach N",
    "Paradise Beach Park",
    "Paradise Cay",
    "San Quentin Beach",
    "Starkweather Park",
    "Pt. San Pablo",
    "Pt. Orient N",
    "Pt. Orient S",
    "Pt. Molate",
    "Keller Beach",
    "Miller Knox"
  )
)
```


```{r Fig.X, fig.width = 5, fig.height = 8,}
sizes3 %>%   
  ggplot(aes(y=site_name, x=size_mm,  fill=site_name)) +
   geom_density_ridges(alpha=0.8, stat="binline", bins=10) +
   theme_ridges() +
     theme(
         legend.position="none",
         panel.spacing = unit(0.1, "lines"),
         strip.text.x = element_text(size = 8)
     ) +
     xlab("") +
     ylab("Assigned Probability (%)") 
```
 

```{r, include=FALSE}
## save figure to output folder
# ggsave(here::here("output","oyster_quad_counts.pdf"), width = 20, height = 20, units = "cm")
```

```{r, include=FALSE}
##what's up with Keller Beach mid zone oyster count?
#used this to figure out outlier issue and correct original data file (was a date entry error). #Updated the file in github with a commit note to explain the change.
#saving code chunk here for reference only

# t1 <- rqs3 %>% 
#   group_by(zone, site_name)%>%
#   summarise(min_cov= min(oyster_n, na.rm = TRUE), Q1=quantile(oyster_n, probs = 0.25, na.rm = TRUE), median_cov = median(oyster_n, na.rm = TRUE), Q3=quantile(oyster_n, probs = 0.75, na.rm = TRUE), max_cov = max(oyster_n, na.rm = TRUE)) %>% 
#   arrange(min_cov, Q1, median_cov, Q3, max_cov)
# t1
```


